<?php
/**
 * @file
 * Fate Groups utility module, including custom functions for dice rolling.
 */

/**
 * Implements hook_update_projects_alter() for update_projects().
 */
function fate_utils_update_projects_alter(&$projects) {
  // We wish to remove our custom modules from any drupal.org updates.
  foreach ($projects as $key => $project) {
    // Most custom module match this naming convention.
    if (preg_match('/^fate_.*$/', $key)) {
      unset($projects[$key]);
    }
  }
}

/**
 * Implements hook_comment_presave().
 */
 
 # TODO check for the field_roll_modifier field type and instance attached to the comment entity
 
function fate_utils_comment_presave($comment) {
	if (!$comment->field_roll['und'][0]['value'] && is_null($comment->field_roll_modifier['und'][0]['value'])==false) {
	
	$firstdie = (rand(0,2))-1;
	$seconddie = (rand(0,2))-1;
	$thirddie = (rand(0,2))-1;
	$fourthdie = (rand(0,2))-1;
	
	$modifier = $comment->field_roll_modifier['und'][0]['value'];
	
	if ($modifier > 0) {
		$modifier_display = '+'.intval($modifier);
	} else {
		$modifier_display = $modifier;
	}
	
	$roll = $firstdie+$seconddie+$thirddie+$fourthdie+$modifier;
	
	$roll_display = _get_font_awesome_dice($firstdie).' '._get_font_awesome_dice($seconddie).' '._get_font_awesome_dice($thirddie).' '._get_font_awesome_dice($fourthdie);

 		$comment->field_roll['und'][0]['value'] = $roll_display.' with a '.$modifier_display.' added to the roll for a total of: '.$roll. ' ('._ladder($roll).')'; 
 		$comment->field_roll['und'][0][format] = 'full_html'; 
 	}
 }
 
 function fate_utils_node_presave($node) {
 
  if (isset($node->field_roll['und'][0]['value'])) {
 
	if (!$node->field_roll['und'][0]['value'] && is_null($node->field_roll_modifier['und'][0]['value'])==false) {
	
	$firstdie = (rand(0,2))-1;
	$seconddie = (rand(0,2))-1;
	$thirddie = (rand(0,2))-1;
	$fourthdie = (rand(0,2))-1;
	
	$modifier = $node->field_roll_modifier['und'][0]['value'];
	
	if ($modifier > 0) {
		$modifier_display = '+'.intval($modifier);
	} else {
		$modifier_display = $modifier;
	}
	
	$roll = $firstdie+$seconddie+$thirddie+$fourthdie+$modifier;
	
	$roll_display = _get_font_awesome_dice($firstdie).' '._get_font_awesome_dice($seconddie).' '._get_font_awesome_dice($thirddie).' '._get_font_awesome_dice($fourthdie);

 		$node->field_roll['und'][0]['value'] = $roll_display.' with a '.$modifier_display.' added to the roll for a total of: '.$roll. ' ('._ladder($roll).')'; 
 		$node->field_roll['und'][0][format] = 'full_html'; 
 	}
 }
 }
 

 
function _get_font_awesome_dice($value) {
	if($value==-1) {$die='<i class="fa fa-minus-square"></i>';}
	if($value==0) {$die='<i class="fa fa-square"></i>';}
	if($value==1) {$die='<i class="fa fa-plus-square"></i>';}
	return $die;
}


function _ladder($value) {
	if($value > 7) {$adjective='Legendary';}
	if($value == 7) {$adjective='Epic';}
	if($value == 6) {$adjective='Fantastic';}
	if($value == 5) {$adjective='Superb';}
	if($value == 4) {$adjective='Great';}
	if($value == 3) {$adjective='Good';}
	if($value == 2) {$adjective='Fair';}
	if($value == 1) {$adjective='Average';}
	if($value == 0) {$adjective='Mediocre';}
	if($value == -1) {$adjective='Poor';}
	if($value < -1) {$adjective='Terrible';}
	return $adjective;
}